"""fitdash on your phone: the dashboard as a web page, served only to your own devices.

    fitdash --html [PATH]        write the dashboard as one HTML page (default ~/.fitbit-mcp/web/index.html)
    fitdash web --install        refresh the page every 30 min and serve it on 127.0.0.1:8787
    fitdash web --status | --uninstall

The server listens on 127.0.0.1 only, so nothing on your Wi-Fi or the internet can reach it.
Tailscale makes it reachable from your phone and nowhere else:

    tailscale serve --bg 8787     → https://<this-mac>.<tailnet>.ts.net on your tailnet only

The page is a static snapshot (no scripts, no external requests), regenerated by a launchd agent
that syncs first when the data is over 30 min old. Everything stays in ~/.fitbit-mcp/web.
"""
from __future__ import annotations

import html
import os
import plistlib
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

PORT = 8787
PHONE_WIDTH = 64                       # columns: readable on a phone in portrait, pinch to zoom
LABELS = {"refresh": "com.fitdash.web.refresh", "server": "com.fitdash.web.server"}

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="fitdash">
<meta name="theme-color" content="#111111">
<meta name="robots" content="noindex">
<title>fitdash</title>
<style>
:root {{ color-scheme: dark; }}
html, body {{ margin: 0; background: #111111; color: #ecebe6; }}
body {{ padding: max(12px, env(safe-area-inset-top)) 8px 24px; }}
.meta {{ font: 12px -apple-system, system-ui, sans-serif; color: #9a9893; margin: 0 4px 8px; }}
pre {{ margin: 0; font-family: ui-monospace, "SF Mono", Menlo, monospace; line-height: 1.2;
      font-size: min(14px, calc((100vw - 16px) / {cols} / 0.6)); white-space: pre; overflow-x: auto; }}
pre span {{ font-family: inherit; }}
/* one terminal cell per glyph: a symbol the phone's monospace font lacks (braille rings, ● ◐ ★ …)
   comes from a fallback font with a different width, which would push the box border out */
pre .c {{ display: inline-block; width: 1ch; height: 1.2em; overflow: hidden; vertical-align: top;
         text-align: center; }}
</style></head>
<body><div class="meta">Updated {updated} · pull down to reload</div>
{body}
</body></html>
"""


def default_path(home: Path) -> Path:
    return home / "web" / "index.html"


def to_html(render_fn, width: int = PHONE_WIDTH, updated: str | None = None) -> str:
    """render_fn(console) draws into a recording console; its output becomes inline-styled HTML."""
    from rich.console import Console
    from rich.terminal_theme import TerminalTheme
    rec = Console(record=True, width=width, file=open(os.devnull, "w"), color_system="truecolor",
                  force_terminal=True, highlight=False, emoji=False, soft_wrap=False)
    render_fn(rec)
    theme = TerminalTheme((17, 17, 17), (236, 235, 230), [(0, 0, 0)] * 8, [(128, 128, 128)] * 8)
    body = pin_cells(rec.export_html(theme=theme, inline_styles=True, code_format="<pre>{code}</pre>"))
    return PAGE.format(cols=width, updated=html.escape(updated or datetime.now().strftime("%a %-d %b, %-I:%M %p")),
                       body=body)


def _monospaced_ok(ch: str) -> bool:
    """ASCII, box drawing and block elements are in every monospace font; anything else gets a cell."""
    o = ord(ch)
    return o < 0x80 or 0x2500 <= o <= 0x259F


def pin_cells(body: str) -> str:
    """Wrap every glyph that might fall back to a non-monospace font in a fixed 1ch cell. Only text
    between tags is touched; rich's markup (styles, tags) is plain ASCII."""
    out, in_tag = [], False
    for ch in body:
        if ch == "<":
            in_tag = True
        elif ch == ">":
            in_tag = False
        if in_tag or _monospaced_ok(ch):
            out.append(ch)
        else:
            out.append('<span class="c">' + ch + "</span>")
    return "".join(out)


def write(path: Path, page: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(page)
    tmp.replace(path)                  # atomic: the server never serves half a page


# ---------------------------------------------------------------- launchd agents

def _plist(label: str) -> Path:
    return Path.home() / "Library" / "LaunchAgents" / (label + ".plist")


def _path_env() -> str:
    uv_dir = str(Path(shutil.which("uv") or "/opt/homebrew/bin/uv").parent)
    return ":".join(dict.fromkeys([str(Path.home() / ".local" / "bin"), uv_dir, "/opt/homebrew/bin",
                                   "/usr/local/bin", "/usr/bin", "/bin"]))


def _fitdash() -> list[str]:
    wrapper = shutil.which("fitdash") or str(Path.home() / ".local" / "bin" / "fitdash")
    if Path(wrapper).exists():
        return [wrapper]
    return [shutil.which("uv") or "uv", "run", "--quiet", "--script", str(Path(__file__).with_name("dashboard.py"))]


def _load(label: str, plist: dict) -> bool:
    domain = "gui/{}".format(os.getuid())
    subprocess.run(["launchctl", "bootout", domain + "/" + label], capture_output=True)
    p = _plist(label)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "wb") as f:
        plistlib.dump(plist, f)
    r = subprocess.run(["launchctl", "bootstrap", domain, str(p)], capture_output=True, text=True)
    if r.returncode != 0:
        print("launchctl bootstrap {} failed: {}".format(label, r.stderr.strip()), file=sys.stderr)
    return r.returncode == 0


def install(home: Path, every_min: int = 30) -> int:
    web = default_path(home).parent
    web.mkdir(parents=True, exist_ok=True)
    log = str(home / "web.log")
    py = shutil.which("python3") or "/usr/bin/python3"
    ok = _load(LABELS["server"], {
        "Label": LABELS["server"],
        "ProgramArguments": [py, "-m", "http.server", str(PORT), "--bind", "127.0.0.1", "--directory", str(web)],
        "KeepAlive": True, "RunAtLoad": True, "StandardOutPath": log, "StandardErrorPath": log,
    })
    ok = _load(LABELS["refresh"], {
        "Label": LABELS["refresh"],
        "ProgramArguments": _fitdash() + ["--html", str(default_path(home))],
        "StartInterval": every_min * 60, "RunAtLoad": True,
        "EnvironmentVariables": {"PATH": _path_env()}, "StandardOutPath": log, "StandardErrorPath": log,
    }) and ok
    if not ok:
        return 1
    print("page refreshes every {} min → {}".format(every_min, default_path(home)))
    print("served on http://127.0.0.1:{} (this Mac only)".format(PORT))
    ts = tailscale_bin()
    if ts:
        print("for your phone, run once:  {} serve --bg {}".format(ts, PORT))
    else:
        print("for your phone: install Tailscale, then run once:  tailscale serve --bg {}".format(PORT))
    print("remove with: fitdash web --uninstall")
    return 0


def uninstall() -> int:
    for label in LABELS.values():
        subprocess.run(["launchctl", "bootout", "gui/{}/{}".format(os.getuid(), label)], capture_output=True)
        p = _plist(label)
        if p.exists():
            p.unlink()
    print("web page agents removed (if you ran `tailscale serve`, stop it with: tailscale serve reset)")
    return 0


def tailscale_bin() -> str | None:
    for cand in (shutil.which("tailscale"), "/Applications/Tailscale.app/Contents/MacOS/Tailscale"):
        if cand and Path(cand).exists():
            return cand
    return None


def status(home: Path) -> int:
    for name, label in LABELS.items():
        loaded = subprocess.run(["launchctl", "print", "gui/{}/{}".format(os.getuid(), label)],
                                capture_output=True).returncode == 0
        print("{:<8} {}".format(name, "running" if loaded else "not installed"))
    page = default_path(home)
    if page.exists():
        age = (datetime.now().timestamp() - page.stat().st_mtime) / 60
        print("page     {} ({:.0f} min old)".format(page, age))
    ts = tailscale_bin()
    if not ts:
        print("phone    Tailscale not installed")
    else:
        r = subprocess.run([ts, "serve", "status"], capture_output=True, text=True)
        print("phone    " + (r.stdout.strip().splitlines()[0] if r.returncode == 0 and r.stdout.strip()
                             else "not served yet: {} serve --bg {}".format(ts, PORT)))
    return 0
